### ISSUE TITLE
No HDMI support

### ISSUE THREAD

**Issue by nicolas314** [anaelorlinski/OpenWrt-NanoPi-R5S-Builds#1]
Very nice, thanks for putting this together!
Seems the current version does not include support for HDMI output, which would be really convenient to see what is happening without having to connect a serial probe. I tried installing the panfrost kernel module but it fails due to a kernel version mismatch. Any idea how to bypass that? Thanks!

**Comment by anaelorlinski** [comment]
Will check if I can make this work

**Comment by anaelorlinski** [comment]
Implemented in OpenWrt 23.04 2023.04.25
HDMI output of console is activated in Linux kernel
USB keyboard gives access to console too
However it seems that device sometimes reboot when you hotplug the keyboard

**Comment by nicolas314** [comment]
You did it! Just tested: works fine with HDMI screen and USB keyboard. Makes it genuinely easy to manage the router.
Thanks a lot for all the good work and prompt reaction!
