### ISSUE TITLE
Build guide

### ISSUE THREAD

**Issue by shshekhar93** [anaelorlinski/OpenWrt-NanoPi-R5S-Builds#15]
This is more of a question than issue.

Is there a build guide for this project. I see already built images in the releases, however, I am not able to install most of the packages using opkg. Is it possible to build the project including all packages locally, so that I can install packages from local source?

**Comment by anaelorlinski** [comment]
This repo is a wrapper repository to build images with github actions while adding some patches. You can run manually the scripts in openwrt-23.05/steps/ in a machine with all dependencies needed to build openwrt.
And if you wish you can add extra packages to build and include in the images (make menuconfig), please refer for official OpenWrt build documentation for all the details.

**Comment by shshekhar93** [comment]
One last clarification, when I install this image (self built or prebuilt), will I be able to install (non kmod) packages from Official OpenWrt repos? Or do I need to include each package at build time?

**Comment by anaelorlinski** [comment]
Non kmod packages should work without issues.
