### ISSUE TITLE
Q&A: R3S support?

### ISSUE THREAD

**Issue by rdslw** [anaelorlinski/OpenWrt-NanoPi-R5S-Builds#17]
Hi,

do you plan to start R3S repo? Shall be quiet similar (easy?) to R5S due to similar cpu.

https://www.friendlyelec.com/index.php?route=product/product&path=69&product_id=303

https://forum.openwrt.org/t/openwrt-support-for-nanopi-r3s/

**Comment by anaelorlinski** [comment]
Hi!
This should not be too hard if it's already supported by another distribution like ImmortalWrt because they have the good patches usually. Since I don't own a device it would be too much work without possibility to test.
