### ISSUE TITLE
OpenWrt 23.05.0-rc1

### ISSUE THREAD

**Issue by bohdan-s** [anaelorlinski/OpenWrt-NanoPi-R5S-Builds#4]
Any chance if a OpenWrt 23.05.0-rc1 build?

**Comment by anaelorlinski** [comment]
Yup it's planned !

**Comment by anaelorlinski** [comment]
it's a 23.05 branch build : https://github.com/anaelorlinski/OpenWrt-NanoPi-R5S-Builds/releases/tag/OpenWrtAO-23.05-20230621

I will make another release when rc2 is out

**Comment by bohdan-s** [comment]
Thanks. Working well.
