### ISSUE TITLE
Data being sent to openwrt.ai

### ISSUE THREAD

**Issue by bohdan-s** [anaelorlinski/OpenWrt-NanoPi-R5S-Builds#6]
I just set up a forward DNS on my OpenWRT r5s (using your latest build) and noticed a lot of calls out to openwrt.ai

Do you know what these lookups might be for?

**Comment by anaelorlinski** [comment]
I am very surprised with that, because my builds are based on vanilla OpenWrt source plus some patches that are copied in this repo so all the sources are available.
Can you verify you are really running my build ? with cat /etc/banner for example

**Comment by bohdan-s** [comment]
I am using the 23.05 2023.08.22 build. But i was using others previously.
I couldn't see any references in your repo (or even any linked repos/source).

Tonight I will do a full reset and re-image and reconfigure from scratch (no backups), at this point it seems more likely some package or config from a previous build is doing the lookups not your firmware.

I will close this issue and re-open if its not resolved with the reset.

**Comment by bohdan-s** [comment]
Just to properly close this off. I opened the backup I restored and found references to openwrt.ai. It seems to be a package config from when I tested ImmortalWRT.
Lesson learned, 1 don't restore configs between firmware changes, 2. look before raising a issue.

@anaelorlinski  Thank you for your build, it has been stable and works well while waiting until officially supported.
