### ISSUE TITLE
How to resize root fs?

### ISSUE THREAD

**Issue by ghost** [anaelorlinski/OpenWrt-NanoPi-R5S-Builds#7]
I have installed the latest build of OpenWrt from here on the internal eMMC of a R5S via upload in FriendlyWrt web-interface. For now the system boots up and seems to work fine - thank you!
Unfortunately it is using just 1G of the eMMC:

root@OpenWrt:~# fdisk /dev/mmcblk1
...
Disk /dev/mmcblk1: 28.91 GiB, 31037849600 bytes, 60620800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos

Device         Boot  Start     End Sectors Size Id Type
/dev/mmcblk1p1 *     65536  147455   81920  40M 83 Linux
/dev/mmcblk1p2      196608 2293759 2097152   1G 83 Linux

root@OpenWrt:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                88.3M     88.3M         0 100% /rom
tmpfs                     1.8G    936.0K      1.8G   0% /tmp
/dev/loop0              933.9M     72.8M    861.1M   8% /overlay
overlayfs:/overlay      933.9M     72.8M    861.1M   8% /
tmpfs                   512.0K         0    512.0K   0% /dev
cgroup                    1.8G         0      1.8G   0% /sys/fs/cgroup
overlayfs:/overlay      933.9M     72.8M    861.1M   8% /opt/docker

How can I expand the filesystem to use the whole 32G? I found a howto (https://openwrt.org/docs/guide-user/advanced/expand_root)  but I get no errors and it seems not to do anything. What do I miss?

Thanks in advance.

**Comment by anaelorlinski** [comment]
This might help https://github.com/anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds/blob/main/docs/resize-f2fs.md

**Comment by ghost** [comment]
Sorry, I could have found that myself :-(
It worked - thank you. And thank you again for your great work!
